# Generated by Django 5.0.1 on 2024-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='username',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='username',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
