# Generated by Django 5.0.1 on 2024-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_mentorprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
