# Generated by Django 5.0.1 on 2024-03-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mentorprofile_full_name_recruiterprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
