# Generated by Django 5.0.1 on 2024-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_companyprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
