# Generated by Django 5.0.1 on 2024-03-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_companyprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, default='profile_photos/Default_icon.jpg', upload_to='company_logos/'),
        ),
    ]
