# Generated by Django 5.0.1 on 2024-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date_of_application',
            field=models.CharField(max_length=255),
        ),
    ]
