# Generated by Django 5.0.1 on 2024-04-20 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_jobapplication_applied_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_users',
        ),
        migrations.AddField(
            model_name='job',
            name='applied_users',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Applied Users'),
        ),
    ]
