# Generated by Django 5.0.1 on 2024-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
