# Generated by Django 5.0.1 on 2024-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_course_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='course_covers/'),
        ),
    ]
