# Generated by Django 5.0.1 on 2024-03-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_remove_note_chapter_note_course_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enroll',
        ),
    ]
