# Generated by Django 5.0.1 on 2024-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_remove_course_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
