# Generated by Django 5.0.1 on 2024-04-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_remove_note_content_note_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
