# Generated by Django 5.0.1 on 2024-04-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0011_chapter_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='progress',
        ),
    ]
