# Generated by Django 5.0.1 on 2024-04-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_engagementprogress_verificationprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementprogress',
            old_name='engagement_percentage',
            new_name='engaged_frames',
        ),
        migrations.AddField(
            model_name='engagementprogress',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
    ]
